 mailman-core:
   image: timimages/mailman-core:latest
   restart: unless-stopped
   volumes:
     - ./mailman/db:/opt/mailmandb
     - ./mailman/core/logs:/opt/mailman/var/logs
     - ./mailman/plugins:/plugins
   environment:
     DATABASE_TYPE: sqlite
     DATABASE_URL: sqlite:////opt/mailmandb/mailmanweb.db
     DATABASE_CLASS: mailman.database.sqlite.SQLiteDatabase
     HYPERKITTY_API_KEY: test
     HYPERKITTY_URL: http://mailman-web:8000/mailman3/hyperkitty/
     INIT_DEV: 1
     TIM_DEV: 1
 mailman-web:
   image: timimages/mailman-web:latest
   restart: unless-stopped
   depends_on:
     - mailman-core
   volumes:
     - ./mailman/db:/opt/mailmandb
     - ./mailman/web:/opt/mailman-web-data
     - ./mailman/messages:/tmp/mailman-messages
     - ./mailman/plugins:/plugins
   environment:
     DATABASE_TYPE: sqlite
     DATABASE_URL: sqlite:////opt/mailmandb/mailmanweb.db
     DATABASE_CLASS: mailman.database.sqlite.SQLiteDatabase
     HYPERKITTY_API_KEY: test
     SECRET_KEY: test
     MAILMAN_ADMIN_USER: admin
     MAILMAN_ADMIN_EMAIL: admin@example.com
     SERVE_FROM_DOMAIN: localhost
     URL_BASE_DIR: mailman3
     TIM_DEV: 1