name: Run tests

on: push

jobs:
  ci_tests:
    name: CI tests (${{ matrix.test_module }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_module:
          - browser
          - unit
          - db
          - server
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            timApp/node_modules
            timApp/modules/jsrunner/server/node_modules
          key: ${{ runner.os }}-ci-test-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Log info
        run: |
          uname -a
          docker info
          docker-compose --version
      # Run install steps manually to better capture run time
      - name: Set up
        run: ./tim setup --no-interactive --no-install --profile test
      - name: Download images
        run: ./tim dc pull --quiet
      - name: Install dependencies
        run: ./tim npmi
      - name: Compile JS
        run: ./tim js
      - name: Run tests
        run: ./tim test --dc-up ${{ matrix.test_module }}
        timeout-minutes: 40
      - name: Upload screenshots
        if: "${{ matrix.test_module == 'browser' && always() }}"
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Browser Screenshots
          path: screenshots